spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://user-service:8080
            predicates:
              - Path=/users/**
            filters:
              -PrefixPath=/api/v1

server:
  port: 9000
