spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://user-service:8080
            predicates:
              - Path=/api/v1/users/**
              - Method=GET,POST

          - id: order_service
            uri: http://order-service:8082
            predicates:
              - Path=/api/v1/order/**
server:
  port: 9000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

